/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GrapheneUi {
    'endPoint': string;
  }
}

declare global {


  interface HTMLGrapheneUiElement extends Components.GrapheneUi, HTMLStencilElement {}
  var HTMLGrapheneUiElement: {
    prototype: HTMLGrapheneUiElement;
    new (): HTMLGrapheneUiElement;
  };
  interface HTMLElementTagNameMap {
    'graphene-ui': HTMLGrapheneUiElement;
  }
}

declare namespace LocalJSX {
  interface GrapheneUi {
    'endPoint'?: string;
  }

  interface IntrinsicElements {
    'graphene-ui': GrapheneUi;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'graphene-ui': LocalJSX.GrapheneUi & JSXBase.HTMLAttributes<HTMLGrapheneUiElement>;
    }
  }
}


